apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: In-memory-database/creds
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: In-memory-database/creds
        property: password